apiVersion: v1
kind: Service
metadata:
  name: {{ include "roleplaying.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "roleplaying.name" . }}
    helm.sh/chart: {{ include "roleplaying.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app.kubernetes.io/name: {{ include "roleplaying.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
