nameOverride: ""
fullnameOverride: ""

image:
  repository: 789163415875.dkr.ecr.eu-west-2.amazonaws.com/pmckenna25/rpgame
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80

container:
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 512Mi

environment:
  name: qa

nodeSelector: {}

ingress:
  enabled: true
  host: roleplaying.philipmckenna.co.uk
  secret: roleplaying-tls

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

mysql:
  enabled: true
  imageTag: 5.7
  MYSQL_DATABASE: Roleplaying
  MYSQL_USER: admin
  MYSQL_PASSWORD: password1234

  persistence:
    size: 1Gi

# TODO add mysql dependency and pvc
# currently this would deploy the service
# without any database and therefore not
# function as intended
