nameOverride: ""
fullnameOverride: ""

image:
  repository: pmckenna25/roleplaying
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80

container:
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 512Mi

environment:
  name: qa

nodeSelector: {}

ingress:
  enabled: false
  # host: roleplaying.co.uk
  # secret: roleplaying-tls

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

mysql:
  enabled: true
  imageTag: 5.7
  mysqlDatabase: Roleplaying
  mysqlUser: admin
  mysqlPassword: password1234

  persistence:
    size: 1Gi
