#!/usr/bin/env groovy
node() {
  try{

    stage('Checkout'){
      checkout scm
    }

    def gitHash = sh(returnStdout: true, script: "git rev-parse --short HEAD").trim()
    def tag = "789163415875.dkr.ecr.eu-west-2.amazonaws.com/pmckenna25/rpgame:$gitHash"

    stage('Smoke test'){
      sh '/usr/local/bin/docker-compose build smoke'
      sh '/usr/local/bin/docker-compose run smoke'
      sh '/usr/local/bin/docker-compose down'
    }

    withCredentials([string(credentialsId: 'ecrRegistry', variable: 'ECR_REGISTRY')]) {
      stage('Tag and Push to ECR') {
        sh "docker build . -t $tag"
        sh "docker push $tag" 
      }
    }

  }catch(error){
    sh '/usr/local/bin/docker-compose down'
    throw error
  }
}
