#!/usr/bin/env groovy
node() {
  try{
    stage('Checkout'){
      checkout scm
    }
    stage('Smoke test'){
      sh 'usr/local/bin/docker-compose build smoke'
      sh 'usr/local/bin/docker-compose run smoke'
      sh 'usr/local/bin/docker-compose down'
    }
  }catch(error){
    sh 'usr/local/bin/docker-compose down'
    throw error
  }
}
